version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=shashi
      - MONGO_INITDB_ROOT_PASSWORD=shashi10
  mongo-express:
    image: mongo-express
    container_name: mongo

    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=shashi
      - ME_CONFIG_MONGODB_ADMINPASSWORD=shashi10
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  data: {}
networks:
  default:
    name: mongodb_network
